name: Nightly Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          
      - name: Update nightly tag
        uses: EndBug/latest-tag@latest
        if: github.ref == 'refs/heads/main'
        with:
          ref: nightly
      
      - name: Collect all files
        run: |
          mkdir ./RaidTables
          mkdir -p ./RaidTables/libs/LibDeflate
          mkdir -p ./RaidTables/libs/LibSerialize
          mkdir -p ./RaidTables/libs/LibStub
          cp -r ./RaidTables.lua ./RaidTables.toc ./embeds.xml ./LICENSE ./README.md ./RaidTables
          cp -r ./libs/LibDeflate/LibDeflate.lua ./libs/LibDeflate/LICENSE.txt ./RaidTables/libs/LibDeflate/
          cp -r ./libs/LibSerialize/LibSerialize.lua ./libs/LibSerialize/LICENSE ./RaidTables/libs/LibSerialize/
          cp -r ./libs/LibStub/LibStub.lua ./RaidTables/libs/LibStub/
          zip -r RaidTables-Nightly.zip ./RaidTables
          tar -czvf RaidTables-Nightly.tar.gz ./RaidTables
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          name: Nightly
          tag_name: nightly
          files: |
            RaidTables-Nightly.zip
            RaidTables-Nightly.tar.gz
