name: Nightly Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
env:
  VERSION: "0.1.0"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          
      - name: Update ${{ env.VERSION }} tag
        uses: EndBug/latest-tag@latest
        if: github.ref == 'refs/heads/main'
        with:
          ref: release-${{ env.VERSION }}
      
      - name: Collect all files
        run: |
          mkdir ./RaidTables
          mkdir -p ./RaidTables/libs/LibDeflate
          mkdir -p ./RaidTables/libs/LibSerialize
          mkdir -p ./RaidTables/libs/LibStub
          cp -r ./RaidTables.lua ./RaidTables.toc ./embeds.xml ./RaidTables
          cp -r ./libs/LibDeflate/LibDeflate.lua ./RaidTables/libs/LibDeflate/
          cp -r ./libs/LibSerialize/LibSerialize.lua ./RaidTables/libs/LibSerialize/
          cp -r ./libs/LibStub/LibStub.lua ./RaidTables/libs/LibStub/
          zip -r RaidTables-${{ env.VERSION }}.zip ./RaidTables
          tar -czvf RaidTables-${{ env.VERSION }}.tar.gz ./RaidTables
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: ${{ env.VERSION }}
          tag_name: release-${{ env.VERSION }}
          files: RaidTables-${{ env.VERSION }}.zip
