name: Release Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Collect all files
        run: |
          mkdir ./RaidTables
          mkdir -p ./RaidTables/libs/LibDeflate
          mkdir -p ./RaidTables/libs/LibSerialize
          mkdir -p ./RaidTables/libs/LibStub
          mkdir -p ./RaidTables/libs/LibUIDropDownMenu
          mkdir -p ./RaidTables/img
          cp -r ./RaidTables.lua ./RaidTables.toc ./embeds.xml ./LICENSE ./README.md ./RaidTables
          cp -r ./img/RaidTables.png ./RaidTables/img/
          cp -r ./libs/LibDeflate/LibDeflate.lua ./libs/LibDeflate/LICENSE.txt ./RaidTables/libs/LibDeflate/
          cp -r ./libs/LibSerialize/LibSerialize.lua ./libs/LibSerialize/LICENSE ./RaidTables/libs/LibSerialize/
          cp -r ./libs/LibStub/LibStub.lua ./RaidTables/libs/LibStub/
          cp -r ./libs/LibUIDropDownMenu/LibUIDropDownMenu.lua ./RaidTables/libs/LibUIDropDownMenu/
          zip -r RaidTables-${{ github.ref_name }}.zip ./RaidTables
          tar -czvf RaidTables-${{ github.ref_name }}.tar.gz ./RaidTables
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            RaidTables-${{ github.ref_name }}.zip
            RaidTables-${{ github.ref_name }}.tar.gz
